version: 0.1.0-pre{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  publish_nuget: true
  verbosity: minimal

before_build:
  - nuget restore

artifacts:
  - path: **\*.nupkg